version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: pa_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_analyser
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./backend/sql:/sql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pa_api
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/sql:/sql

volumes:
  dbdata:
